### PR TITLE
Add support for Python 3

### PR DESCRIPTION
**Pull request by zxiiro**
I'm looking into using this library and am happy to help provide support for Python 3. I'll try to make sure my changes are backwards compatible with Python 2 as well.

### CODE REVIEW

**Comment by dpursehouse** [comment]
Thanks for the contribution.  I'm no longer maintaining this library; development was moved to [pygerrit2](https://github.com/dpursehouse/pygerrit2) and there are a couple of commits there to support python 3.

Note that pygerrit2 only supports REST.  Support for SSH was removed.

**Comment by zxiiro** [comment]
Why has SSH support removed in pygerrit2?

The feature we're most interested in from this library is the ssh stream-events feature so I think pygerrit2 will be a no go for us. We're still evaluating our options so I'm not yet sure what library stack will ultimately use but if we do decide to go with pygerrit would it be alright if I picked up maintenance of this package so that we can add support for the parts we need?

**Comment by dpursehouse** [comment]
> Why has SSH support removed in pygerrit2?

Most clients should be using REST these days. Apart from the noticeable absence of any stream-events equivalent, the REST API provides more functionality than SSH.

Also since the clients I'm writing (and plan to write in future) only use REST, I wanted to make the library installation a bit more lightweight.  Removing SSH support also removes the dependency on paramiko, pycrypto and friends.

> would it be alright if I picked up maintenance of this package so that we can add support for the parts we need?

I'd be fine with that, but I don't actually own this repository so can't add you.  Since I left Sony I'm not sure if anyone else has been assigned to work on it.  I'll try to find out.

**Comment by zxiiro** [comment]
>Also since the clients I'm writing (and plan to write in future) only use REST, I wanted to make the library installation a bit more lightweight. Removing SSH support also removes the dependency on paramiko, pycrypto and friends.

Thanks that makes sense.

> I'd be fine with that, but I don't actually own this repository so can't add you. Since I left Sony I'm not sure if anyone else has been assigned to work on it. I'll try to find out.

Thanks I appreciate that, worst case I can likely strip down the ssh part of the library into a new module but I do prefer to work upstream when possible.

**Comment by zaro0508** [comment]
zxiiro, as an alternative you might want to consider gerritlib[1] since it does pretty much everything thru the ssh interface. Although I do actually like David's pygerrit better since it supports both REST and ssh.  The docs are at https://gerritlib.readthedocs.io/en/latest/  

[1] https://git.openstack.org/cgit/openstack-infra/gerritlib

**Comment by choldrim** [comment]
hi @dpursehouse , I think you should add the `No Longer Maintaining` label on the `README.md`, and lead us to [pygerrit2](https://github.com/dpursehouse/pygerrit2)

**Comment by dpursehouse** [comment]
@choldrim good point.  I've done that in 89578cb65abc4cdaa41304663ed9ef206794b681.

I can't update the project description though.  I don't have permissions to do that.

**Comment by zxiiro** [comment]
Hi @dpursehouse I'm guessing no word from Sony about passing on maintainership of this package?

I'm only interested in the stream-events code I may fork the project and strip it down to just that for my needs in the worst case.

**Comment by dpursehouse** [comment]
@zxiiro sorry I haven't had chance to follow up on this yet.

Pinging @huaxings -- do you know if anyone is working on this now?

**Comment by yiu31802** [comment]
@dpursehouse , as far as i know, no one is actively enhancing pygerrit currently at Sony Mobile.

**Comment by huaxings** [comment]
@dpursehouse, unfortunately no one is really assigned and allocated for maintaining this package.

**Comment by dpursehouse** [comment]
@zxiiro sorry for the delay.  I've finally got confirmation from Sony that it will be possible to add you as a maintainer of this.  I'll send a separate email with details.

**Pull request closed without merging**
